name: build dbup-cli

on:
  workflow_call:
    inputs:
      gitversion_mmp:
        required: true
        type: string
      gitversion_nuget:
        required: true
        type: string
    secrets:
      FC_REPO_CHECKOUT_ALL:
        required: true
      FC_PACKAGE_AUTH_READ_TOKEN:
        required: true
      FC_PACKAGE_AUTH_ALL_TOKEN:
        required: true

defaults:
  run:
    shell: pwsh

jobs:

  build:
    runs-on: [self-hosted, ubuntu-20.04]

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FC_REPO_CHECKOUT_ALL }}
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        env:
          DOTNET_INSTALL_DIR: ~/.dotnet
        with:
          dotnet-version: 9.0.x

      - name: Determine the build configuration
        shell: pwsh
        run: ./.github/scripts-common/dotnet/set-build-configuration.ps1

      - name: Clean the build directory
        run: dotnet clean --configuration ${{ env.DOTNET_BUILD_CONFIGURATION }}

      - name: Restore dependencies
        env:
          FC_PACKAGE_AUTH_READ_TOKEN: ${{ secrets.FC_PACKAGE_AUTH_READ_TOKEN }}
        run: dotnet restore ./src/dbup-cli

      - name: Build
        run: |
          dotnet build `
            --no-restore `
            -c ${{ env.DOTNET_BUILD_CONFIGURATION }} `
            -p:Version=${{ inputs.gitversion_mmp }} `
            -p:DebugSymbols=true -p:DebugType=embedded `
            ./src/dbup-cli

      - name: Test
        run: dotnet test --no-build --verbosity normal ./src/dbup-cli

      - name: Package
        if: github.ref_name == 'main' || startsWith(github.ref_name, 'feature/')
        run: |
          dotnet pack `
            --no-restore `
            -c ${{ env.DOTNET_BUILD_CONFIGURATION }} `
            -p:Version=${{ inputs.gitversion_mmp }} `
            -p:DebugSymbols=true `
            -p:DebugType=embedded `
            -p:PackageVersion=${{ inputs.gitversion_nuget }} `
            ./src/dbup-cli

      - name: Push
        if: github.ref_name == 'main' || startsWith(github.ref_name, 'feature/')
        env:
          FC_PACKAGE_AUTH_READ_TOKEN: ${{ secrets.FC_PACKAGE_AUTH_ALL_TOKEN }}
        run: |
          dotnet nuget push `
          ./src/dbup-cli/nupkg/**.nupkg `
            --source github `
            --skip-duplicate